project:
  type: website
execute:
  freeze: auto
website:
  title: "Julia for large scale geospatial analysis"
  favicon: logo.svg
  navbar:
    background: dark
    tools:
        - icon: github
          href: https://github.com/felixcremer/BiDS2025_JuliaTutorial
    right:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    style: "docked"
    search: true
    contents:
    - href: "index.qmd"
      text: Home
    - section: "Julia Introduction"
      contents:
      - intro-julia.qmd
      - href: intro-pkg.qmd
        text: Package Manager
    - href: "geo-ecosystem.qmd"
      text: Geo Ecosystem
    - section: "Raster data analysis"
      contents:
      - DimensionalData.qmd
      - DimensionalEngine.qmd
author:
  - name: Felix Cremer
    affiliations: 
    - ref: mpi
  - name: Lazaro Alonso
    affiliations: 
    - ref: mpi
  - name: Anshul Singhvi
    affiliations: 
    - ref: jlhub
  - name: Fabian Gans
    affiliations: 
    - ref: mpi
affiliations:
- id: jlhub
  name: JuliaHub
- id: mpi
  name: Max Planck Institute for Biogeochemistry
format:
  html:
    code-fold: false
theme:
  light: flatly
  dark: darkly
toc: true
number-sections: true
engines: ['julia']

